//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace QuanLyBanHang.Module.BusinessObjects.QuanLyBanHang
{

    public partial class DoiTuong : XPLiteObject
    {
        int fId;
        [Key(true)]
        [MemberDesignTimeVisibility(false)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        string fMa;
        [Indexed(Name = @"IX_DoiTuong", Unique = true)]
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Mã")]
        public string Ma
        {
            get { return fMa; }
            set { SetPropertyValue<string>("Ma", ref fMa, value); }
        }
        string fTen;
        [Indexed(Name = @"IX_DoiTuong_1", Unique = true)]
        [DevExpress.Xpo.DisplayName(@"Tên")]
        public string Ten
        {
            get { return fTen; }
            set { SetPropertyValue<string>("Ten", ref fTen, value); }
        }
        string fDiaChi;
        [Size(200)]
        [DevExpress.Xpo.DisplayName(@"Địa chỉ")]
        public string DiaChi
        {
            get { return fDiaChi; }
            set { SetPropertyValue<string>("DiaChi", ref fDiaChi, value); }
        }
        string fDienThoaiBan;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Điện thoại bàn")]
        public string DienThoaiBan
        {
            get { return fDienThoaiBan; }
            set { SetPropertyValue<string>("DienThoaiBan", ref fDienThoaiBan, value); }
        }
        string fDienThoaiDiDong;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Điện thoại di động")]
        public string DienThoaiDiDong
        {
            get { return fDienThoaiDiDong; }
            set { SetPropertyValue<string>("DienThoaiDiDong", ref fDienThoaiDiDong, value); }
        }
        string fEmail;
        [Size(50)]
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>("Email", ref fEmail, value); }
        }
        string fWebsite;
        [Size(50)]
        public string Website
        {
            get { return fWebsite; }
            set { SetPropertyValue<string>("Website", ref fWebsite, value); }
        }
        string fMaSoThue;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Mã số thuế")]
        public string MaSoThue
        {
            get { return fMaSoThue; }
            set { SetPropertyValue<string>("MaSoThue", ref fMaSoThue, value); }
        }
        bool fLaNhaCungCap;
        [DevExpress.Xpo.DisplayName(@"Là Nhà cung cấp")]
        public bool LaNhaCungCap
        {
            get { return fLaNhaCungCap; }
            set { SetPropertyValue<bool>("LaNhaCungCap", ref fLaNhaCungCap, value); }
        }
        bool fLaKhachHang;
        [DevExpress.Xpo.DisplayName(@"Là Khách hàng")]
        public bool LaKhachHang
        {
            get { return fLaKhachHang; }
            set { SetPropertyValue<bool>("LaKhachHang", ref fLaKhachHang, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Nhập hàng hóa")]
        [Association(@"NhapReferencesDoiTuong")]
        public XPCollection<Nhap> Nhaps { get { return GetCollection<Nhap>("Nhaps"); } }
        [DevExpress.Xpo.DisplayName(@"Nhập đầu kỳ")]
        [Association(@"NhapDauKyReferencesDoiTuong")]
        public XPCollection<NhapDauKy> NhapDauKies { get { return GetCollection<NhapDauKy>("NhapDauKies"); } }
        [Association(@"XuatReferencesDoiTuong")]
        public XPCollection<Xuat> Xuats { get { return GetCollection<Xuat>("Xuats"); } }
    }

}
