//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace QuanLyBanHang.Module.BusinessObjects.QuanLyBanHang
{

    public partial class HangHoa : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        string fMa;
        [Indexed(Name = @"IX_HangHoa", Unique = true)]
        [Size(50)]
        public string Ma
        {
            get { return fMa; }
            set { SetPropertyValue<string>("Ma", ref fMa, value); }
        }
        string fMa1;
        [Indexed(Name = @"IX_HangHoa_2", Unique = true)]
        [Size(50)]
        public string Ma1
        {
            get { return fMa1; }
            set { SetPropertyValue<string>("Ma1", ref fMa1, value); }
        }
        string fMa2;
        [Indexed(Name = @"IX_HangHoa_3", Unique = true)]
        [Size(50)]
        public string Ma2
        {
            get { return fMa2; }
            set { SetPropertyValue<string>("Ma2", ref fMa2, value); }
        }
        string fMaVach;
        [Size(50)]
        public string MaVach
        {
            get { return fMaVach; }
            set { SetPropertyValue<string>("MaVach", ref fMaVach, value); }
        }
        string fTen;
        [Indexed(Name = @"IX_HangHoa_1", Unique = true)]
        [Size(200)]
        public string Ten
        {
            get { return fTen; }
            set { SetPropertyValue<string>("Ten", ref fTen, value); }
        }
        int fDonViTinh_Id;
        public int DonViTinh_Id
        {
            get { return fDonViTinh_Id; }
            set { SetPropertyValue<int>("DonViTinh_Id", ref fDonViTinh_Id, value); }
        }
        decimal fGia;
        public decimal Gia
        {
            get { return fGia; }
            set { SetPropertyValue<decimal>("Gia", ref fGia, value); }
        }
        string fGhiChu;
        [Size(200)]
        public string GhiChu
        {
            get { return fGhiChu; }
            set { SetPropertyValue<string>("GhiChu", ref fGhiChu, value); }
        }
        bool fSuDung;
        public bool SuDung
        {
            get { return fSuDung; }
            set { SetPropertyValue<bool>("SuDung", ref fSuDung, value); }
        }
        [Association(@"Nhap_HangHoaReferencesHangHoa")]
        public XPCollection<Nhap_HangHoa> Nhap_HangHoas { get { return GetCollection<Nhap_HangHoa>("Nhap_HangHoas"); } }
        [Association(@"NhapDauKy_HangHoaReferencesHangHoa")]
        public XPCollection<NhapDauKy_HangHoa> NhapDauKy_HangHoas { get { return GetCollection<NhapDauKy_HangHoa>("NhapDauKy_HangHoas"); } }
        [Association(@"Xuat_HangHoaReferencesHangHoa")]
        public XPCollection<Xuat_HangHoa> Xuat_HangHoas { get { return GetCollection<Xuat_HangHoa>("Xuat_HangHoas"); } }
    }

}
