//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace QuanLyBanHang.Module.BusinessObjects.QuanLyBanHang
{

    public partial class Nhap_HangHoa : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        Nhap fNhap_Id;
        [Association(@"Nhap_HangHoaReferencesNhap")]
        public Nhap Nhap_Id
        {
            get { return fNhap_Id; }
            set { SetPropertyValue<Nhap>("Nhap_Id", ref fNhap_Id, value); }
        }
        HangHoa fHangHoa_Id;
        [Association(@"Nhap_HangHoaReferencesHangHoa")]
        public HangHoa HangHoa_Id
        {
            get { return fHangHoa_Id; }
            set { SetPropertyValue<HangHoa>("HangHoa_Id", ref fHangHoa_Id, value); }
        }
        decimal fSoLuong;
        public decimal SoLuong
        {
            get { return fSoLuong; }
            set { SetPropertyValue<decimal>("SoLuong", ref fSoLuong, value); }
        }
        DonViTinh fDonViTinh_Id;
        [Association(@"Nhap_HangHoaReferencesDonViTinh")]
        public DonViTinh DonViTinh_Id
        {
            get { return fDonViTinh_Id; }
            set { SetPropertyValue<DonViTinh>("DonViTinh_Id", ref fDonViTinh_Id, value); }
        }
        decimal fGiaNhap;
        public decimal GiaNhap
        {
            get { return fGiaNhap; }
            set { SetPropertyValue<decimal>("GiaNhap", ref fGiaNhap, value); }
        }
        Ke fKe_Id;
        [Association(@"Nhap_HangHoaReferencesKe")]
        public Ke Ke_Id
        {
            get { return fKe_Id; }
            set { SetPropertyValue<Ke>("Ke_Id", ref fKe_Id, value); }
        }
        string fGhiChu;
        [Size(200)]
        public string GhiChu
        {
            get { return fGhiChu; }
            set { SetPropertyValue<string>("GhiChu", ref fGhiChu, value); }
        }
    }

}
