//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace QuanLyBanHang.Module.BusinessObjects.QuanLyBanHang
{

    public partial class NhapDauKy_HangHoa : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        int fNhap_Id;
        [MemberDesignTimeVisibility(false)]
        public int Nhap_Id
        {
            get { return fNhap_Id; }
            set { SetPropertyValue<int>("Nhap_Id", ref fNhap_Id, value); }
        }
        HangHoa fHangHoa_Id;
        [Association(@"NhapDauKy_HangHoaReferencesHangHoa")]
        [DevExpress.Xpo.DisplayName(@"Hàng hóa")]
        public HangHoa HangHoa_Id
        {
            get { return fHangHoa_Id; }
            set { SetPropertyValue<HangHoa>("HangHoa_Id", ref fHangHoa_Id, value); }
        }
        decimal fSoLuong;
        [DevExpress.Xpo.DisplayName(@"Số lượng")]
        public decimal SoLuong
        {
            get { return fSoLuong; }
            set { SetPropertyValue<decimal>("SoLuong", ref fSoLuong, value); }
        }
        DonViTinh fDonViTinh_Id;
        [Association(@"NhapDauKy_HangHoaReferencesDonViTinh")]
        [DevExpress.Xpo.DisplayName(@"Đơn vị tính")]
        public DonViTinh DonViTinh_Id
        {
            get { return fDonViTinh_Id; }
            set { SetPropertyValue<DonViTinh>("DonViTinh_Id", ref fDonViTinh_Id, value); }
        }
        decimal fGiaNhap;
        [DevExpress.Xpo.DisplayName(@"Giá nhập")]
        public decimal GiaNhap
        {
            get { return fGiaNhap; }
            set { SetPropertyValue<decimal>("GiaNhap", ref fGiaNhap, value); }
        }
        Ke fKe_Id;
        [Association(@"NhapDauKy_HangHoaReferencesKe")]
        [DevExpress.Xpo.DisplayName(@"Kệ")]
        public Ke Ke_Id
        {
            get { return fKe_Id; }
            set { SetPropertyValue<Ke>("Ke_Id", ref fKe_Id, value); }
        }
        string fGhiChu;
        [Size(200)]
        [DevExpress.Xpo.DisplayName(@"Ghi chú")]
        public string GhiChu
        {
            get { return fGhiChu; }
            set { SetPropertyValue<string>("GhiChu", ref fGhiChu, value); }
        }
        NhapDauKy fNhapDauKy_Id;
        [Association(@"NhapDauKy_HangHoaReferencesNhapDauKy")]
        public NhapDauKy NhapDauKy_Id
        {
            get { return fNhapDauKy_Id; }
            set { SetPropertyValue<NhapDauKy>("NhapDauKy_Id", ref fNhapDauKy_Id, value); }
        }
    }

}
