//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace QuanLyBanHang.Module.BusinessObjects.QuanLyBanHang
{

    public partial class Xuat_HangHoa : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        Xuat fXuat_Id;
        [Association(@"Xuat_HangHoaReferencesXuat")]
        public Xuat Xuat_Id
        {
            get { return fXuat_Id; }
            set { SetPropertyValue<Xuat>("Xuat_Id", ref fXuat_Id, value); }
        }
        HangHoa fHangHoa_Id;
        [Association(@"Xuat_HangHoaReferencesHangHoa")]
        public HangHoa HangHoa_Id
        {
            get { return fHangHoa_Id; }
            set { SetPropertyValue<HangHoa>("HangHoa_Id", ref fHangHoa_Id, value); }
        }
        decimal fSoLuong;
        public decimal SoLuong
        {
            get { return fSoLuong; }
            set { SetPropertyValue<decimal>("SoLuong", ref fSoLuong, value); }
        }
        DonViTinh fDonViTinh_Id;
        [Association(@"Xuat_HangHoaReferencesDonViTinh")]
        public DonViTinh DonViTinh_Id
        {
            get { return fDonViTinh_Id; }
            set { SetPropertyValue<DonViTinh>("DonViTinh_Id", ref fDonViTinh_Id, value); }
        }
        decimal fGiaXuat;
        public decimal GiaXuat
        {
            get { return fGiaXuat; }
            set { SetPropertyValue<decimal>("GiaXuat", ref fGiaXuat, value); }
        }
        string fGhiChu;
        [Size(200)]
        public string GhiChu
        {
            get { return fGhiChu; }
            set { SetPropertyValue<string>("GhiChu", ref fGhiChu, value); }
        }
    }

}
